spring:
  application:
    name: api-Gateway

  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\{segment}
        - id: booking
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<segment>.*), /$\{segment}
        - id: supplier-service
          uri: lb://supplier-service
          predicates:
            - Path=/supplier/**


server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true